services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    expose:
      - 5432
    networks:
      - gomes-estudos-spring-udemy
    volumes:
      - postgres_data:/var/lib/postgresql/data

  startup:
    image: gomestkd/startup
    restart: always
    build: ./startup
    working_dir: /startup
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - gomes-estudos-spring-udemy

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - gomes-estudos-spring-udemy

volumes:
  postgres_data:
    driver: local
  portainer_data:
    driver: local

networks:
  gomes-estudos-spring-udemy:
    driver: bridge
