name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build Application .jar
      working-directory: ./startup
      run: mvn clean package -DskipTests

    - name: Running Application
      working-directory: ./startup
      run: mvn spring-boot:run

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose up -d --build

    - name: Push to Docker Hub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/startup:latest ${{ secrets.DOCKER_USERNAME }}/startup:${{ github.run_id }}
        docker compose push ${{ secrets.DOCKER_USERNAME }}/startup:latest
        docker compose push ${{ secrets.DOCKER_USERNAME }}/startup:${{ github.run_id }}
